name: somenewsfound
services:
  app:
    build: .
    image: ghcr.io/taoi11/somenewsfound:main
    container_name: somenewsfound-app
    environment:
      - NODE_ENV=production
      - DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/somenewsfound
      - DEPLOYMENT_ENV=production
    restart: unless-stopped