version: '3.8'

services:
  app:
    build: .
    container_name: somenewsfound-app
    environment:
      - NODE_ENV=production
      - DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/somenewsfound
      - DEPLOYMENT_ENV=production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped