version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    environment:
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV:-development}
    command: npm run ${NODE_ENV:-dev}
    restart: unless-stopped 